### ISSUE TITLE
Location wrapper returns case-sensitivity port, hostname and protocol in the href field (T272552) 

### ISSUE THREAD

**Issue by churkin** [superroma/testcafe-hammerhead#1]
Proxied page - `http://localhost:1401/!2/http://Example.com/`.

`location.href` should returns `http://example.com` instead of `http://Example.com`

**Comment by inikulin** [comment]
Is this behavior consistent across browsers? Can't find it in [URL spec] (https://url.spec.whatwg.org/#dom-urlutils-hostname) (`Location` interface is inherited from `URLUtils` per [living DOM spec]()https://html.spec.whatwg.org/multipage/browsers.html#location).

**Comment by churkin** [comment]
Browser sends requests with host, port, protocol in the lower case

**Comment by inikulin** [comment]
All browsers?

**Comment by churkin** [comment]
I have checked IE, FF, Chrome

**Comment by inikulin** [comment]
OK then

**Comment by inikulin** [comment]
fixed via 76d52329aa79b460df3f46288fdb21cfa16d4df2
