### ISSUE TITLE
Get all constant values to a identical type

### ISSUE THREAD

**Issue by churkin** [superroma/testcafe-hammerhead#111]

**Comment by inikulin** [comment]
For the context: 
I think we need some common pattern for all our DOM-integrated constants, with some naming convention with clear names, because currently it's pretty random and not clear. I think we can do it in separate PR after v1.0, can you fill the issue pls?

**Comment by inikulin** [comment]
E.g., turn this
```js
const IFRAME_WINDOW_INITED = 'hh_iwi_5d9138e9';
```
into
```js
const IFRAME_WINDOW_INITED = '%hammerhead|iframe-window-inited%';
```
