### ISSUE TITLE
Transform instance-level constants to the ctor properties

### ISSUE THREAD

**Issue by churkin** [superroma/testcafe-hammerhead#112]
`constructor () {`
`this.UNCAUGHT_JS_ERROR = 'uncaughtJSError';`

to

`WindowSandbox.UNCAUGHT_JS_ERROR_EVENT = 'uncaughtJSError';`

**Comment by inikulin** [comment]
It's will be not in proto in this case, but in ctor. I'll edit the title

**Comment by churkin** [comment]
We decided not to implement it because of the inconvenience of use
