### ISSUE TITLE
Use the native XMLHttpRequest instead of a SERVICE_MSG_REQUEST_FLAG flag mechanism

### ISSUE THREAD

**Issue by churkin** [superroma/testcafe-hammerhead#113]
@inikulin wrote:
>We have a SERVICE_MSG_REQUEST_FLAG in https://github.com/churkin/testcafe->hammerhead/blob/es6/src/client/sandbox/xhr/index.js . It was used to skip tracking of the transport >messages. I'm wondering, since we use native methods now, do we still need this flag?

**Comment by LavrovArtem** [comment]
I'm working on this
