### ISSUE TITLE
How uploading works on the Linux/MacOS platforms?

### ISSUE THREAD

**Issue by churkin** [superroma/testcafe-hammerhead#115]
In the Hammerhead we are using windows-specific code:

`const FAKE_PATH_STRING         = 'C:\\fakepath\\';`

We should investigate how it works on other platforms.

**Comment by inikulin** [comment]
\cc @LavrovArtem

**Comment by LavrovArtem** [comment]
http://www.w3schools.com/jsref/prop_fileupload_value.asp
> This property returns the name of the selected file with a fake path in IE, Google Chrome, and Opera, and the name of the selected file in Firefox and Safari.

**Comment by inikulin** [comment]
@LavrovArtem How it's related?

**Comment by inikulin** [comment]
The question is why we have `FAKE_PATH_STRING`, how it used and why it equals to the Windows-specific path?

**Comment by LavrovArtem** [comment]
http://dev.w3.org/html5/spec-preview/common-input-element-apis.html#common-input-element-apis
>**filename**
>On getting, it must return the string "C:\fakepath\" followed by the filename of the first file in the list of selected files, if any, or the empty string if the list is empty. On setting, if the new value is the empty string, it must empty the list of selected files; otherwise, it must throw an InvalidStateError exception.

>This "fakepath" requirement is a sad accident of history. See [the example in the File Upload state section](http://dev.w3.org/html5/spec-preview/states-of-the-type-attribute.html#fakepath-srsly) for more information.

**Comment by inikulin** [comment]
Lol, I see now. BTW use WHATWG HTML and Living DOM specs instead of W3C's.
Can we include the comment in the code with the link to https://html.spec.whatwg.org/multipage/forms.html#fakepath-srsly ? This will make situation much cleaner.

**Comment by LavrovArtem** [comment]
Yes of course
