### ISSUE TITLE
Create badge for the Health Monitor like we have for Travis

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#118]

**Comment by miherlosev** [comment]
Badge mockup
![hh_badge_mockup](https://cloud.githubusercontent.com/assets/4133518/10131418/c53806d6-65d8-11e5-933a-28f06b3a3629.png)

**Comment by LavrovArtem** [comment]
I think that Events and Resources aren't necessery.

**Comment by inikulin** [comment]
I think we need just one badge with the most important information:
1.Relative load event time
2.Number of errors

Task should fail if error rate increases for 10% and if performance degrades. Bot should automatically fill an issue in case of regression (\cc @AlexanderMoskovkin )

**Comment by miherlosev** [comment]
see updated badge:
![updated_hh_badge](https://cloud.githubusercontent.com/assets/4133518/10131717/0812bac6-65db-11e5-94cc-97ead7f6a3ae.png)

**Comment by inikulin** [comment]
I'd prefer to have two badges instead of one if they will have separate statuses (one for error and one for performance). It would be nice to have current limit for the errors as well.

**Comment by miherlosev** [comment]
![0812bac6-65db-11e5-94cc-97ead7f6a3ae](https://cloud.githubusercontent.com/assets/4133518/10131906/38655d68-65dc-11e5-809c-33c7d37c69d2.png)

**Comment by miherlosev** [comment]
Badge with real data (see markdown)
/cc @inikulin @churkin 

[![Hammerhead Health Monitor](http://testcafedemo.devexpress.com:13500/badge/last-commit.svg)](http://testcafedemo.devexpress.com:13500)

**Comment by inikulin** [comment]
@miherlosev I like the information, but we need better visual design. Let's ping our designer

**Comment by churkin** [comment]
1. '35 errors' --> '35 sites with errors'
2. Maybe something like 'Slowing down page load: 1,24x (limit - 1.40x)' ?

**Comment by inikulin** [comment]
@churkin I like it as is, this should have max information within minimum space
\cc @VasilyStrelyaev

**Comment by churkin** [comment]
@inikulin what does `1.24` mean? seconds? minutes? I would not understand.

**Comment by VasilyStrelyaev** [comment]
I would go with:
Sites: 35 errors (limit: 21)
Page load: 1.24x (limit: 1.40x)

**Comment by inikulin** [comment]
@VasilyStrelyaev factor sign always goes before value, e.g.: `x1.24 `

**Comment by VasilyStrelyaev** [comment]
dunno, speed is kind of 1.5x, 2x, ...

**Comment by VasilyStrelyaev** [comment]
in our case, it's probably clearer to use x1.24

**Comment by inikulin** [comment]
@miherlosev BTW we can remove `Hammerhead` from the badge title, so it will be just `Health Monitor`

**Comment by miherlosev** [comment]
> @miherlosev BTW we can remove `Hammerhead` from the badge title, so it will be just `Health Monitor`

Yes

Final text:
Health Monitor
Commit: 93cbf61 (September 28, 13:52:48)
Sites: 35 errors (limit: 21)
Page load: 1.24x (limit: 1.40x)

**Comment by inikulin** [comment]
@miherlosev Should be:
```
Page load: x1.24 (limit: x1.40)
```

**Comment by miherlosev** [comment]
Updated badge:
[![Hammerhead Health Monitor](http://testcafedemo.devexpress.com:13500/badge/last-commit.svg)](http://testcafedemo.devexpress.com:13500)

**Comment by miherlosev** [comment]
GitHub proxies all non-https images (our badge goes over http) - https://github.com/blog/1766-proxying-user-images.
I've asked the GutHub support team (https://github.com/contact) if we can create a badge that goes over http. 
I've discussed a badge design with the designer. He promises to create the badge today.

**Comment by miherlosev** [comment]
GitHub Support Team answear:
Re: Aggresive caching badge over http protocol
Hi,

No, you cannot disable our Camo image proxy. We documented the full details of how it works here:

https://help.github.com/articles/why-do-my-images-have-strange-urls

> I have a badge - http://testcafedemo.devexpress.com:13500/badge/last-commit.svg
> It was added to the page - https://github.com/superroma/testcafe-hammerhead/issues/118/#issuecomment-144084982.
> A badge date differs for a badge added via markup (https://github.com/superroma/testcafe-hammerhead/issues/118/#issuecomment-144084982) and a badge opened in a separate browser tab (http://testcafedemo.devexpress.com:13500/badge/last-commit.svg)
> I found that GitHub caches all non-http images (https://github.com/blog/1766-proxying-user-images).
>
> Does GitHub allow badges over HTTP? Can I disable user image proxing?

**Comment by inikulin** [comment]
So, we need to serve it over https, right?

**Comment by miherlosev** [comment]
Yes. 
I am trying to use self-signed sertificate.
But it causes 'ERR_CERT_AUTHORITY_INVALID'
To reproduce - https://testcafedemo.devexpress.com:13501/badge/last-commit.svg.

**Comment by inikulin** [comment]
Ask internal team guys, maybe we can use our cert somehow to serve it

**Comment by miherlosev** [comment]
Ok

**Comment by miherlosev** [comment]
Badge design: ![health-monitor](https://cloud.githubusercontent.com/assets/4133518/10225104/d1f09eae-6869-11e5-85d5-fed4415555c6.png)

**Comment by inikulin** [comment]
Looks fine, kinda...

**Comment by miherlosev** [comment]
> Ask internal team guys, maybe we can use our cert somehow to serve it
Internal team guys say that domain 'testcafedemo.devexpress.com' will be moved to https (as all other public sites)

**Comment by inikulin** [comment]
@miherlosev Can we move just our health monitor domain to https? Keeping site on 80th port (testcafedemo.devexpress.com) with http protocol?

**Comment by miherlosev** [comment]
HealthMonitor will be avalible on separate domain - 'https://testcafe-hhhm.devexpress.com'

**Comment by miherlosev** [comment]
Final badge:
[![Hammerhead Health Monitor](https://testcafe-hhhm.devexpress.com/badge/last-commit.svg)](http://https://testcafe-hhhm.devexpress.com)

**Comment by inikulin** [comment]
It has wrong URL and can we change the font?

**Comment by miherlosev** [comment]
Font and wrong url were fixed
