### ISSUE TITLE
Implement API to add a ShadowUI suffix to css rules for the injectable stylesheets

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [superroma/testcafe-hammerhead#129]
Hammehread should have API to process css files (add a suffix to css rules).

It's necessary to fix the https://github.com/superroma/testcafe-phoenix/issues/54 issue

**Comment by inikulin** [comment]
Actually, it shouldn't have any specific API. It should automatically process and cache session's `injectable` stylesheets.

**Comment by inikulin** [comment]
It can be done via `isShadowUIStylesheet` flag, which passed to the router on the resource registration (see: https://github.com/superroma/testcafe-hammerhead/blob/master/src/proxy.js#L71). Then move logic what will modify CSS to the `src/shadow-ui` dir. We can put shadowUI [related constants](https://github.com/superroma/testcafe-hammerhead/blob/master/src/const.js#L25)  to the separate file in that dir, as part of #68
