### ISSUE TITLE
module.exports in client code

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#130]
https://github.com/superroma/testcafe-hammerhead/blob/master/src/client/utils/browser.js#L37 - I'm not sure if this works. Anyway, we should get rid of this approach, which replaces exports.

**Comment by inikulin** [comment]
Well, it's kinda works - webmake passes require to module. However, it's not ES6 syntax compatible and we shouldn't use it in our code (except for `require` in `index.js` for testing purposes, but we still need comment which describes this behavior where).

**Comment by inikulin** [comment]
We have a breaking change introduced: `browserUtils.isMozilla` -> `browserUtils.isFirefox`. @churkin Please, publish updated version. @AlexanderMoskovkin switch testcafe to this version taking in consideration BC.

**Comment by churkin** [comment]
I suggest to accumulate a few important fixes before publication

**Comment by inikulin** [comment]
@churkin Ok, can you create milestone for the release and mark related issues?
