### ISSUE TITLE
Add stack trace information for failed tests

### ISSUE THREAD

**Issue by miherlosev** [superroma/testcafe-hammerhead#137]
QUnit contains stack trace information:
![1](https://cloud.githubusercontent.com/assets/4133518/10157760/b35dda22-6695-11e5-83af-e238e339e85e.png)

Sauce Labs doesn't contain this information:
![1](https://cloud.githubusercontent.com/assets/4133518/10157752/980415d4-6695-11e5-8572-1b25403f1b5b.png)

**Comment by AlexanderMoskovkin** [comment]
fixed in qunit-harness
