### ISSUE TITLE
Upload dialog shows up in MS Edge

### ISSUE THREAD

**Issue by AndreyBelym** [superroma/testcafe-hammerhead#147]
After recording test with upload in MS Edge on DevExtreme [Filemanager Demo Page]( http://demos.devexpress.com/ASPxFileManagerAndUploadDemos/FileManager/Features.aspx) file select dialog shows up when executing step clicking on file choose button.

**Comment by AndreyBelym** [comment]
Steps to reproduce the problem:
1. Start recording at http://demos.devexpress.com/ASPxFileManagerAndUploadDemos/FileManager/Features.aspx
2. Click 'Browse' button.
3. Select a file.
4. Click upload button.
5. Now try to play recorded test. At step 'Click Browse button' you will be prompted to select a file again.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Cann't reproduce - http://screencast.com/t/pbmSh60MtOYg

**Comment by churkin** [comment]
@AndreyBelym Please, try to reproduce the problem after upgrade hammerhead to v.1.0.0.

**Comment by AndreyBelym** [comment]
Confirmed, I can't reproduce the bug too after update.
