### ISSUE TITLE
Selection sandbox doesn't work properly

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [superroma/testcafe-hammerhead#149]
`Selection` sandbox depends on `FocusBlurSandbox` but the instance of `FocusBlurSandbox` is `null` when `EventSandbox` creates the instance of `Selection` sandbox

The issue stops https://github.com/superroma/testcafe-phoenix/issues/44

**Comment by inikulin** [comment]
@churkin I believe we will find more issues like this. The best solution will be #101 implementation.
