### ISSUE TITLE
Figure out why we need JSON processing. And remove it if it's unnecessary.

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#15]
I've also seen a part of it in the `js-processor`

**Comment by inikulin** [comment]
ref #5

**Comment by churkin** [comment]
B237743. Vestiges of the past.

**Comment by inikulin** [comment]
What about https://github.com/superroma/testcafe-hammerhead/blob/master/src/processing/js/index.js#L130 ?

**Comment by inikulin** [comment]
I'm working on it

**Comment by inikulin** [comment]
jsProcessor was removed from the client API. `hammerhead.navigateTo(url)` was introduced.
