### ISSUE TITLE
Check specified scenario on pre-release version

### ISSUE THREAD

**Issue by miherlosev** [superroma/testcafe-hammerhead#151]
Step to reproduce:
1)Open page http://js.devexpress.com/Demos/WidgetsGallery/#lite/data_grid-columns-column_customization in playground in IE11.
2)Click 'Column Chooser' button
3)Close 'Column Chooser' dialog

There must be no script errors.

Wait for https://github.com/superroma/testcafe-phoenix/issues/44

**Comment by inikulin** [comment]
Any update on this?

**Comment by inikulin** [comment]
\cc @miherlosev @churkin @LavrovArtem

**Comment by miherlosev** [comment]
It will be checked late.
Need to invent a quit test.

**Comment by inikulin** [comment]
@miherlosev We need to do that ASAP, it's blocking 1.0.0 release

**Comment by LavrovArtem** [comment]
not reproduced

**Comment by inikulin** [comment]
good
