### ISSUE TITLE
QUnit tests for style utils fails in MacOS Chrome

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#158]
Surprisingly, MacOS Chrome differs from the Windows version and style tests fail there (I assume what it is related to the drawing differences). Let's add Chrome and Firefox MacOS browsers to the SauceLabs browse matrix. \cc @churkin @miherlosev We need to do this for testcafe as well \cc @AlexanderMoskovkin

**Comment by inikulin** [comment]
\cc @miherlosev Any update on this? Can we add browsers to the browser matrix?

**Comment by miherlosev** [comment]
> Can we add browsers to the browser matrix?

Yes, we can.
I will do it now.
