### ISSUE TITLE
Use `es6-promisify` instead of our own promisify implementation

### ISSUE THREAD

**Issue by AndreyBelym** [superroma/testcafe-hammerhead#164]
Note on `es6-promisify`: there is a difference between it and `Promise.denodeify` (and our own `promisify` implementation).

If node-style function has callback with conventional  two arguments `(error, data)`, everything is identical: Promises returned from both `es6-promisify` and `Promise.denodeify` resolve `data`, and reject `error`. But if callback is called with more arguments, like callback of [request](https://www.npmjs.com/package/request) function - `(error, response, body)`, then function promisified with `es6-promisify` will resolve array `[response, body]`, unlike `Promise.denodeify` and our own `promisify`, that resolves just `response`.

**Comment by miherlosev** [comment]
`es6-promisify` initially trying to use native Promise.
see https://github.com/digitaldesignlabs/es6-promisify/blob/master/lib/promise.js.
In node 0.10 `es6-promisify` will be use `es6-promise`, for node version >= 0.12 it will be use native Promise. It is not consistent.
I think we should not use `es6-promisify` implementation.
If we need support callback with more than two parameters I can improove own implementatation.
it's very simple:
Need change code for https://github.com/superroma/testcafe-hammerhead/blob/master/src/utils/promisify.js
from
```javascript
args.push((err, res) => {
                if (err)
                    reject(err);
                else
                    resolve(res);
 });
```
to
```javascript
 args.push((...callbackArgs) => {
                var err = callbackArgs[0];

                if (err)
                    reject(err);
                else {
                    callbackArgs = callbackArgs.slice(1);
                    resolve(callbackArgs.length > 1 ? callbackArgs : callbackArgs[0]);
                }
            });
```

**Comment by inikulin** [comment]
> In node 0.10 es6-promisify will be use es6-promise, for node version >= 0.12 it will be use native Promise. It is not consistent.

It's completely OK. The only reason we use es6 promise on servers side is because of node 10

**Comment by miherlosev** [comment]
Ok. Then we should to use Promise on client side if possibe.
Chrome, FF, MSEge has a Promise support.

**Comment by inikulin** [comment]
@miherlosev No, we shouldn't. It can polyfilled or replaced by testable page (the same reasons why we don't use native JSON).
