### ISSUE TITLE
Refactor the structure of the client sandboxes

### ISSUE THREAD

**Issue by churkin** [superroma/testcafe-hammerhead#17]
\cc @LavrovArtem @miherlosev 

Based on https://github.com/superroma/testcafe-hammerhead/issues/5

- [ ] Exclude 'sandboxes' entity to the 'sandboxes.js' file
- [ ] Simplify dom sandbox to the node sandbox
- [ ] Make "sandboxes" entity a point of entry for all sandboxes
- [ ] Rename `sandboxes` to `sandbox`
- [ ] Get rid of `init` methods and use ctors instead
- [ ] Let main sandbox construct other parts and pass instances to the ctors instead of `require`-approach.

**Comment by inikulin** [comment]
We can just have `index.js` in the `client/sanboxes`
