### ISSUE TITLE
Create API which will provide infrastructure for the cross-lib interaction

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#18]
Think how hammerhead can be safely exposed to TestCafe scripts: provide non-enumerable window property which will contain all script getters (without setters). You can call it `app.js`. Each module will take it's reference of the app from the `window`.
E.g. in `test-cafe/ui.js`:

```js
var hammerhead = window['@TestCafe@'].getLib('hammerhead');
window['@TestCafe@'].registerLib('test-cafe-ui', exports);
```
\cc @AlexanderMoskovkin 

ref #5

**Comment by inikulin** [comment]
...or, we can do it simply this way:

```js
Object.defineProperty(window, '@hammerhead@', {
  enumerable: false,
  configurable: false,
  writable: false,
  value: exports
});
```

For the test cafe core:
```js
Object.defineProperty(window, '@testCafeCore@', {
  enumerable: false,
  configurable: false,
  writable: false,
  value: exports
});
```
etc.

I prefer this way, since we don't add any magic entities, and just make things simple and straightforward.

What do you think?

**Comment by AlexanderMoskovkin** [comment]
The last way looks nice. We can start with it. We should use it in the hammerhead also.

But the `@moduleName@` naming looks not pretty for me. 
```js
var hammerhead = window['@hammerhead@']
```

Maybe something like `window.@moduleName` or anything else? Or it's ok?

**Comment by AlexanderMoskovkin** [comment]
After a discussion with @inikulin @churkin  we've taken a decision:

`hammerhead` defines the property `window.[%testcafe%]` and it is used as a dictionary to share modules api, consts etc..

**Comment by inikulin** [comment]
Important note: property should be defined as shown above (non-enumerable, etc.)
