### ISSUE TITLE
Let's rethink our Promise lib (once again =))

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#189]
What I don't like currently:
- es6-promise lib, because we need to do [this](https://github.com/superroma/testcafe-hammerhead/blob/master/Gulpfile.js#L135) and it's quite big. I found nice, small, browser-compatible alternative which doesn't pollute global scope: https://github.com/floatdrop/pinkie Ideal candidate for client-side usage.
- testcafe also uses es6-promises which is required by each it's client module. So we have a lot if copies of the same module on client side. Hammerhead should expose it's Promise in API, so it can be used by testcafe.
- on server side we could use same library OR just abandon node 10 support and use native promises (I starting to think more and more in regard of this option)

**Comment by inikulin** [comment]
Ok, I've seen couple of errors caused by es6-promise AMD in HHM (like we had in #127). So, I'm raising priority of this.

**Comment by inikulin** [comment]
@churkin Release 1.1.0 please

**Comment by churkin** [comment]
@inikulin  https://github.com/superroma/testcafe-hammerhead/pull/220
