### ISSUE TITLE
Setup client tests for all platforms

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#19]
We need to add Mac Safari, iOS Safari, Android browsers

**Comment by inikulin** [comment]
ref #5

**Comment by churkin** [comment]
@miherlosev is already working on this

**Comment by inikulin** [comment]
I just see that the code was fixed, but CI env was not setup for this platforms (also, I don't see mentions of the MacOS Safari). So I'll keep this issue open for now, till we'll not have this things done.

**Comment by miherlosev** [comment]
\cc @inikulin 
I think you can close issue.
Was added 
IPhone (IOS 7.1), Mac Safari 8.0, IPad 8.1
Android 5.1 (Sauce labs not contains image for Android 5.0)

**Comment by inikulin** [comment]
Ok. Great job though.
