### ISSUE TITLE
Hammerhead.upload doesn't work properly

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [superroma/testcafe-hammerhead#193]
Hammerhead.upload published [here](https://github.com/superroma/testcafe-hammerhead/blob/master/src/client/index.js#L40):
```js
this.upload = this.sandbox.upload.upload;
```
but it should be:
```js
this.upload = this.sandbox.upload.upload.bind(this.sandbox.upload);
```
to have the correct context in the `UploadSandbox.upload` function

**Comment by inikulin** [comment]
I'd prefer to rename UploadSandox `upload` method to `doUpload` to avoid disambiguation.
