### ISSUE TITLE
Update eslint version to 1.0.0

### ISSUE THREAD

**Issue by churkin** [superroma/testcafe-hammerhead#22]
We should update eslint version for using "qunit" env

**Comment by inikulin** [comment]
Seems like we can do it already, since gulp-eslint 1.0 is already released.

**Comment by churkin** [comment]
@inikulin  Yes, I have tried to quickly update but faced with new errors

**Comment by inikulin** [comment]
We have eslint/eslint#3226 now. Waiting for fix. :weary:

**Comment by inikulin** [comment]
We can switch now. Things to do on switch:
1. Switch `curly` rule to the `multi-or-nest` mode and set warning level to `2`.
2. Remove conditional comments which disabled buggy `indent`.

See also: superroma/testcafe-phoenix#43

**Comment by inikulin** [comment]
\cc @churkin @LavrovArtem

**Comment by inikulin** [comment]
Guys, do it ASAP, it's not a big deal. I'm tired of reading long warnings in the build logs.
