### ISSUE TITLE
Prepare NPM publish

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#25]
We need to publish it to NPM, so it can be used by TestCafe package. Fill required package.json fields: description, name, author, copyrights, version, main, files etc. We need to do that as ASAP.

**Comment by inikulin** [comment]
@churkin we need it ASAP

**Comment by churkin** [comment]
@VasilyStrelyaev we need the documentation for the module

**Comment by inikulin** [comment]
@churkin we can do it without docs. Regarding docs - setup jsdoc and document methods, it's a separate issue btw.
