### ISSUE TITLE
Testing infrastructure issues

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#35]
- [x] Sauce labs browser matrix shows state of the last test run (even if it was done in context of PR). We should show state of the last test run in the master branch of the upstream repo only.

- [x] We should include link to the SauceLabs test run into the Travis report.

- [x] Travis timeouts on long running SauceLabs tests (https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/75273832)

**Comment by AlexanderMoskovkin** [comment]
> 3)Travis timeouts on long running SauceLabs tests (https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/75273832)

fixed

**Comment by AlexanderMoskovkin** [comment]
4) Sometimes the gulp-qunit-harness don't get the result of the last saucelabs task, so the travis task hangs for more maximum timeout (more the 2 hours) (https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/76457101)

5) It seems saucelabs can't create several tunnels in short time, so we have a problem when several pull requests are created at the same time. We should create tests queue in the build bot.

6) Sometimes tests hang on the saucelabs vw:
https://saucelabs.com/tests/2a699693c4014909a7f062aea5d2b0f1
https://saucelabs.com/tests/579fe411eed343348c3be0cae3ec1f98
https://saucelabs.com/tests/98b10eede49e4baea8539638a3d34d3c

**Comment by inikulin** [comment]
I think we should handle hangs and service interruptions. In this case we should just re-schedule test runs.

**Comment by inikulin** [comment]
It would be nice to have this ASAP:
> We should include link to the SauceLabs test run into the Travis report.

**Comment by inikulin** [comment]
@AlexanderMoskovkin I've added checkboxes to the issues. Please, check those which are fixed, so we'll be able to track the state of the issue.

**Comment by AlexanderMoskovkin** [comment]
nice

**Comment by AlexanderMoskovkin** [comment]
I've fixed the issues. It seems that testing infrastructure became more stable.
As I understand there are some unstable things on the saucelabs side. I've handled it in the qunit-harness module.
So, I close the issue.
