### ISSUE TITLE
Add the capability to determine the encoding of a resource by using Byte Order Mark (BOM)

### ISSUE THREAD

**Issue by LavrovArtem** [superroma/testcafe-hammerhead#4]
BOM is a Unicode character specifying encoding of a resource. Currently, these characters are not recognized when decoding the resource.
 
It is needed to add the capability to recognize the following BOMs:

| BOM           | Charset              |
| ------------- | -------------------- |
| FE FF         | Big-endian UTF-16    |
| FF FE         | Little-endian UTF-16 |
| EF BB BF      | UTF-8                |
 
When decoding, characters are recognized in the following priority:

1. BOM
2. Content-Type header
3. meta charset
4. default charset

Links to the specification:
* https://html.spec.whatwg.org/#character-encodings
* https://html.spec.whatwg.org/#charset1024

Update the iconv-litle module to be able to work with UTF-16BE encoding.

Create tests for the provided functionality.

**Comment by inikulin** [comment]
That does this mean? Examples? Expected and actual behavior?

**Comment by LavrovArtem** [comment]
For example, if the resource has a BOM FF FE is its charset UTF-16, little-endian

**Comment by LavrovArtem** [comment]
BOM is a Unicode character specifying encoding of a resource. Currently, these characters are not recognized when decoding the resource.
 
It is needed to add the capability to recognize the following BOMs:

| BOM           | Charset              |
| ------------- | -------------------- |
| FE FF         | Big-endian UTF-16    |
| FF FE         | Little-endian UTF-16 |
| EF BB BF      | UTF-8                |
 
When decoding, characters are recognized in the following priority:

1. BOM
2. Content-Type header
3. meta charset
4. default charset

Links to the specification:
* https://html.spec.whatwg.org/#character-encodings
* https://html.spec.whatwg.org/#charset1024

Update the iconv-litle module to be able to work with UTF-16BE encoding.

Create tests for the provided functionality.

**Comment by inikulin** [comment]
Nice! Great job, @LavrovArtem . But can we move all this to the head post of the issue instead of comment?

**Comment by LavrovArtem** [comment]
@inikulin ok

**Comment by inikulin** [comment]
Algorithm differs for the page resources (scripts, css). Please, research it as well.

**Comment by LavrovArtem** [comment]
Priority for the scripts:

1. BOM
2. Content-Type header
3. ```charset``` attribute
4. page charset

Priority is verified on а test page.
