### ISSUE TITLE
Detailed information about failed tests is not shown in Sauce labs 'JSUnit' tab

### ISSUE THREAD

**Issue by miherlosev** [superroma/testcafe-hammerhead#42]
![1](https://cloud.githubusercontent.com/assets/4133518/9304740/037c994e-44f4-11e5-967b-e6f9a04e36a5.png)

**Comment by inikulin** [comment]
\cc @AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
I'll fix it soon

**Comment by AlexanderMoskovkin** [comment]
Fixed in the qunit-harness@0.1.21
