### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#5]
I would like to see 1.0 plan. What is left to do? Can we have separate issues for each item marked with the milesone 1.0? What are farther steps in client refactoring? Which features of ES6 you gonna use?
We need to rename variables as well: new consts notation, new module names notation, etc.

**Comment by inikulin** [comment]
\cc @churkin

**Comment by churkin** [comment]
At the moment hammerhead is completely ready to integrate with the TestCafe, all tests are success 
(instead of Health Monitor, @kirovboris is working on it).
I think we should continue to refactor hammerhead code in the background:
	
	... firstly more global changes

	1. Processing mechanism (separeate to different independent processors). Add tests.
	2. Client sandboxes (exclude 'sandboxes' entity and simplify DomSandbox to the NodeSandbox).
	3. Generate error texts without error codes.
	
	... and after all take the time to code style
	
	4. Investigate the ability to use async/await on the client.	
	5. Check code formating:
		- Rename constants
		- Use arrow functions
		- Rewrite all necessary modules to classes

**Comment by churkin** [comment]
First of all i want to focus on the structural changes

**Comment by inikulin** [comment]
Ok, so let's create issue for each item with the detail description. So we can track progress.

**Comment by inikulin** [comment]
Closing it for now, since the progress can be tracked via Milestone-view: https://github.com/superroma/testcafe-hammerhead/milestones

(don't forget to add milestone to the newly created issues)
