### ISSUE TITLE
Fix error message problems

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#59]
1)Get rid of origin term in texts and remove mentions of proxy
2)Move message.js to the src/
3)We have an inconsistency currently: this errors are expected to be objects in testcafe, but they are strings (formatter, discuss with @kirovboris)

**Comment by kirovboris** [comment]
I think we mustn't use xml format in hammerhead errors. 
Should hammerhead return the error object like test runner? Something like:

```javascript
//Error object
{
    code: ERR.cantResolveUrl,
    originUrl: 'htps://page'
}
```
in templates.js:
```javascript
import {ERR} from 'hammerhead';

[ERR.cantResolveUrl]: (err) => {
    ....
}
```

**Comment by inikulin** [comment]
@kirovboris I'm not quite happy with this approach, which we had before. It would be to simplify errors as much as possible (package should throw error or emit `error` event). So, in `TestRun` in `handlePageError` and create new object where, e.g.:
```js
_handlePageError(ctx, errMsg) {
   var err = { 
       type: ERR_TYPE.networkError,
       msg: errMsg
   };     
     
   this._fatalError(err);
   ctx.redirect(this.browserConnection.idleUrl);
}
```
Doing so, we will not need to expose error types from the hammerhead. @churkin @kirovboris Let me know that do you think?

**Comment by kirovboris** [comment]
Thanks, I agree with it.

**Comment by inikulin** [comment]
@kirovboris I think links is the only thing that we should decorate. I'm ok with the markdown decorator's auto-hyperlinks (but we need special handler in decorator, which will be run on the whole content after the tags processing).
