### ISSUE TITLE
Get rid of shared const.

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#68]
Split `const.js` into the semantically separated groups of constants and put them in the appropriate places. Remove shared const term from the code BTW. As an addition: rename `service-msg-cmd` to `commands` (like with `test-run` in testcafe package) and move it to the `/session` dir with the `session.js` and `cookie.js` (`session.js` being an `index.js` there).

**Comment by miherlosev** [comment]
I think we need to split constans from `const.js` as follow:
1)`DOM_SANDBOX_PROCESSED_CONTEXT`
Using only on client.
Move to `/src/client/utils/dom/.js`
and create two methods:
`getProcessingContext()`
`setProcessingContext(wnd)`
rename to `PROCESSED_CONTEXT`

2)`EVENT_SANDBOX_WHICH_PROPERTY_WRAPPER`
Using only on client.
Move to separate file `/src/client/event/which-property-wrapper.js`
rename to `WHICH_PROPERTY_WRAPPER`


3)`DOM_SANDBOX_OVERRIDE_DOM_METHOD_NAME`
   `DOM_SANDBOX_STORED_ATTR_POSTFIX`
   `HOVER_PSEUDO_CLASS_ATTR`
Using on client and on server.
Move to separate file `/src/processing/dom/attributes.js`
File will be contain these constants and utility functions with them

4)`FOCUS_PSEUDO_CLASS_ATTR`
Using only on client.
Move to separate file and change structure to:
`src/client/sandbox/event/focus-blur/index.js` -  with `focusBlurSandbox`
`src/client/sandbox/event/focus-blur/pseudo-class-attrubute.js`  - with constant

5)`IS_STYLESHEET_PROCESSED_COMMENT`
Using on server and in client tests.
Move to static method of `StyleProcessor`:
`StyleProcessor.hasProcessedComment(text)`
rename to `PROCESSED_COMMENT`

6)`UPLOAD_SANDBOX_HIDDEN_INPUT_NAME`
Using only on client.
Move to `/src/upload/info-hidden-input-name.js`
rename to `INFO_HIDDEN_INPUT_NAME`

7)`DOCUMENT_CHARSET`
Used only on client.
Move to `/src/client/utils/dom.js` and create two methods:
`getDocumentCharset(doc);`
`setDocumentCharset(doc, value)`

/сс @inikulin @churkin please review

**Comment by inikulin** [comment]
Disagree what we should place any constants in utils. Also, I don't like whole file for just single constant, can we make them instance constants, or statics?

**Comment by miherlosev** [comment]
Ok. Updated version:

1)`EVENT_SANDBOX_WHICH_PROPERTY_WRAPPER`
Instace constant - EventSandbox.WHICH_PROPERTY_WRAPPER

2)`DOM_SANDBOX_OVERRIDE_DOM_METHOD_NAME
   DOM_SANDBOX_STORED_ATTR_POSTFIX
   HOVER_PSEUDO_CLASS_ATTR
   DOM_SANDBOX_PROCESSED_CONTEXT,
   FOCUS_PSEUDO_CLASS_ATTR,
  DOCUMENT_CHARSET`
Move to separate file `/src/processing/dom/attributes.js`
Content:
```
export default {
         processedContext: <value>,
         overrideMethodName: <value>,
         storedAttrPostfix: <value>
         hoverPseudoClassAttr: <value>,
         focusPseudoClassAttr: <value>,
         documentCharset: <value>
}
```

3)`IS_STYLESHEET_PROCESSED_COMMENT`
Using on server and in client tests.
Move to static method of `StyleProcessor`:
`StyleProcessor.hasProcessedComment(text)`
rename to `PROCESSED_COMMENT`

4)`UPLOAD_SANDBOX_HIDDEN_INPUT_NAME`
Using on client and on server.
/src/client/sandbox/upload/hidden-info.js
/src/upload/form-data.js
Using in both places to find hidden input with upload info.
I think in this case we need to place into separate file /src/upload/info-hidden-input-name.js
and rename it to `INFO_HIDDEN_INPUT_NAME`
or move to /src/processing/dom/attributes.js (see point 2)

/сс @inikulin @churkin please review again

**Comment by inikulin** [comment]
regarding 2:
We can remove `Attr` from field names, since it will be used as constants union (always with the host object), e.g.:
```js
INTERNAL_ATTRS.focusPseudoClass,
```

I think it should be named `internal-attributes.js` or something like that, since it's our internal, processing-related attrs. @VasilyStrelyaev will help with better naming


regarding 4:
> or move to /src/processing/dom/attributes.js (see point 2)
I vote for this

**Comment by VasilyStrelyaev** [comment]
Well, without actually delving into where they are used, I tend to say "okay". Names seem fair as long as all these constants really have something to do with internal attributes, and abbreviations like `INTERNAL_ATTRS` are allowed according to js style best practices (I still can't get used to it after .NET).
Though we are going to leave `Attr` in `storedAttrPostfix` since it's determinative here, aren't we?
The only thing I doubt about is `overrideMethodName`. What is it actually used for?

**Comment by churkin** [comment]
looks good

**Comment by VasilyStrelyaev** [comment]
Like being ignored so much!

**Comment by inikulin** [comment]
@VasilyStrelyaev :laughing:

**Comment by inikulin** [comment]
Actually we've missed the point here, we definitely should rename `INTERNAL_PROPS.overrideDomMethodName` to `INTERNAL_PROPS.overrideDomMethod`.
\cc @churkin @miherlosev
