### ISSUE TITLE
Integrate health monitor with the git version of the hammerhead

### ISSUE THREAD

**Issue by churkin** [superroma/testcafe-hammerhead#7]
\cc @kirovboris @LavrovArtem 

Based on https://github.com/superroma/testcafe-hammerhead/issues/5

  - [x] Upload health monitor src to mercurial
  - [x] Create farm task
  - [x] Redesign control panel (add 'admin' mode for developers)
  - [x] Open public access to the control panel

**Comment by kirovboris** [comment]
1, 2 - done
Statistics is here - http://66.55.147.18:1350/

**Comment by miherlosev** [comment]
## mockups for 'Health Monitor' pages
Welcome screen
![1_welcomescreen](https://cloud.githubusercontent.com/assets/4133518/9661500/a95b3c36-5263-11e5-950b-51629d149d4a.png)

Login popup
![3_loginscreenpopup](https://cloud.githubusercontent.com/assets/4133518/9661501/a962a4e4-5263-11e5-8f6d-662366049232.png)

Url list
![4_urllist_new](https://cloud.githubusercontent.com/assets/4133518/9661502/a96af054-5263-11e5-8c8a-ce6d477b9b30.png)

**Comment by miherlosev** [comment]
New version of the 'Control Panel' avalible on 'http://66.55.147.18:13500'

**Comment by miherlosev** [comment]
I think we can share 'Control Panel' on 'http://hh.testcafe.devexpress.com'
