### ISSUE TITLE
Prepare code comments

### ISSUE THREAD

**Issue by churkin** [superroma/testcafe-hammerhead#93]

**Comment by inikulin** [comment]
What does this mean?

**Comment by inikulin** [comment]
ping @churkin

**Comment by churkin** [comment]
Check comments with the correctors

**Comment by churkin** [comment]
Progress: https://docs.google.com/document/d/1x2a0qhRIZyEKFMo2MwaueNYoqvWwrSKf1olsyJQPHsY/edit

**Comment by VasilyStrelyaev** [comment]
Completed (disregard notes in the document - I swear it's completed)

**Comment by VasilyStrelyaev** [comment]
@MargaritaLoseva, could you pls grant Andrew the right to accept changes. I think this way it would be more convenient for him to apply our corrections

**Comment by VasilyStrelyaev** [comment]
Oh, it's not your document, it's Andrew's... sorry
