### ISSUE TITLE
Consider extending EventEmitter in sources

### ISSUE THREAD

**Issue by inikulin** [superroma/testcafe-hammerhead#95]
Currently we use `EventEmitter` as class field with the wrapped methods, e.g.: https://github.com/superroma/testcafe-hammerhead/blob/master/src/client/sandbox/base.js

I think we should extend `EventEmitter` in this cases instead. 
\cc @AlexanderMoskovkin I think we need to do this is `testcafe` as well.

BTW currently `src/client/utils/event-emitter` using ES5 syntax, use ES6 classes instead (review other parts of code and check if we have old syntax somewhere else).

**Comment by AlexanderMoskovkin** [comment]
I agree. Should we use the `EventEmitter` class from `hammerhead` api or implement it in `testcafe`?

**Comment by inikulin** [comment]
@AlexanderMoskovkin yep
